name: Build and Test iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: List repository contents
      run: ls -R .
    
    - name: Check project file
      run: |
        ls -l AmorPorFilmesSeries.xcodeproj
        if [ ! -s AmorPorFilmesSeries.xcodeproj ]; then
          echo "Error: Project file is empty or does not exist."
          exit 1
        fi

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app # Ajuste para a versão desejada

    - name: Xcode version
      run: xcodebuild -version

    - name: Install SwiftLint
      run: |
        brew update
        brew install swiftlint

    - name: SwiftLint
      run: swiftlint

    - name: Set up CocoaPods (se necessário)
      run: |
        if test -e Podfile; then
          gem install cocoapods --no-document
          pod install
        fi
        
    - name: Select Xcode
      run: |
        ls -l /Applications/
        sudo xcode-select -switch /Applications/Xcode_16.app
   
   
# Versão instalada no macbook (macOS) é mais atual do que na pipeline do Github Action,
#  por isso pode haver erros
#
#    - name: Build
#      run: xcodebuild clean build
#
#    - name: Run tests
#      run: xcodebuild test
