name: Build and Test iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: List repository contents
      run: ls -R . # O ponto aqui significa o diretório atual do repositório
    # ... o restante dos seus passos ...
    - name: List repository contents
      run: ls -R
    
    - name: Check project file
      run: |
        ls -l AmorPorFilmesSeries.xcodeproj
        if [ ! -s AmorPorFilmesSeries.xcodeproj ]; then
          echo "Error: Project file is empty or does not exist."
          exit 1
        fi

        

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app

    - name: Xcode version
      run: xcodebuild -version

    - name: Install SwiftLint
      run: |
        brew update
        brew install swiftlint

    - name: SwiftLint
      run: swiftlint

    - name: Set up CocoaPods (se necessário)
      run: |
        if test -e Podfile; then
          gem install cocoapods --no-document
          pod install
        fi

    - name: List repository contents
      run: ls -R /Users/runner/work/AmorPorFilmesSeries/AmorPorFilmesSeries/

    - name: Build
      run: xcodebuild clean build -project ~/Users/runner/work/AmorPorFilmesSeries/AmorPorFilmesSeries/AmorPorFilmesSeries.xcodeproj  -scheme AmorPorFilmesSeries -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro'

    - name: Run tests
      run: xcodebuild test -project AmorPorFilmesSeries.xcodeproj -scheme AmorPorFilmesSeriesTests -destination 'platform=iOS Simulator,name=iPhone 16 Pro'
